{ ... }:
{
  imports = [
    ./atuin.nix
    ./bat.nix
    ./btop.nix
    ./carapace.nix
    ./delta.nix
    ./eza.nix
    ./fd.nix
    ./firefox.nix
    ./fzf.nix
    ./gh-dash.nix
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./go.nix
    ./helix.nix
    ./jujutsu.nix
    ./jq.nix
    ./k9s.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./nushell.nix
    ./nvf.nix
    ./opencode.nix
    ./poetry.nix
    ./pyenv.nix
    ./ripgrep.nix
    ./ssh.nix
    ./starship.nix
    ./uv.nix
    ./webapps.nix # NixOS-only (has platform guard inside)
    ./zed.nix
    ./zellij.nix
    ./zsh.nix
    ./zoxide.nix
  ];
}
